services:
  db:
    command:
      - "-c"
      - "shared_buffers=4096MB"
      - "-c"
      - "work_mem=5006kB"
      - "-c"
      - "maintenance_work_mem=1955MB"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "max_worker_processes=19"
      - "-c"
      - "max_parallel_workers_per_gather=4"
      - "-c"
      - "max_parallel_workers=8"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "max_wal_size=1GB"
      - "-c"
      - "min_wal_size=512MB"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements,timescaledb"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_cache_size=11733MB"
      - "-c"
      - "default_statistics_target=500"
      - "-c"
      - "max_locks_per_transaction=128"
      - "-c"
      - "jit=off"
